import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

const inter = Noto_Sans({ weight: ["300", "400", "500", "700"], style: "normal", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
